Apply `.trim()` to strings to fix some properties in classic Quake.
Also add the value to the error for future reference.

Prior to this `e1m2.bsp` and `e1m4.bsp` (I didn't test more) fail to load with:
```
bevy_asset::server: Failed to load asset '.../maps/e1m2.bsp' with asset
loader 'bevy_asset::server::loaders::InstrumentedAssetLoader<bevy_trenchbroom::bsp::loader::BspLoader>':
spawning entity 468 (light): requires property `light` to be a valid `f32` (got `150 `).
Error: invalid float literal
```